### ISSUE TITLE
Error injecting games in DS saves.

### ISSUE THREAD

**Issue by nanashi89** [Difegue/DoujinSoft#11]
[DSMIO.zip](https://github.com/Difegue/DoujinSoft/files/3865640/DSMIO.zip) DS save.

![Screenshot 2019-11-19 13 55 22](https://user-images.githubusercontent.com/23020427/69178036-c7d31500-0ad6-11ea-8a01-cb2e6dfc599e.png) Failed Wii save inject.

**Comment by Difegue** [comment]
Thanks, I'll look at this when I can -- although it's a DS save after all and not a Wii one?

NDS saves can come in weird formats depending on the flashcart, but at the very least the server shouldn't blow up with a 500 if it can't handle the file.
