### ISSUE TITLE
Unable to submit content through DIY Showcase

### ISSUE THREAD

**Issue by tlsctf2** [Difegue/DoujinSoft#13]
I tried to upload a record through DIY Showcase after patching the WAD, but was unable to select DoujinSoft as a recipient. It registered as having a Wii, but not Showcase, and would not let me select it to send the record. At present, I have no way to extract data from WarioWare DIY to upload the record manually.
The website didn't say anything about that being an issue, so I'm going to open an issue about it here. Hope that's alright.

**Comment by Difegue** [comment]
Hmm, can you receive content from the website at least?  
There's been some mess recently with patching games for Wiimmfi usage, so you might want to make sure you patched the WAD with the latest version of the wiiware patcher.  

I personally haven't repatched my own copy of Showcase so I can't test uploads ATM. 
The DoujinSoft server itself isn't attached to a Wii (it's [just emails](https://tvc-16.science/doujinsoft-rc24.html)) and should still work fine.

**Comment by tlsctf2** [comment]
Downloading content from the site and getting shipments is a bit slow, but
works just fine. I just patched my WAD earlier today, so unless an update
got pushed in the last few hours I'm on the latest version.

**Comment by tlsctf2** [comment]
Update: just tried it again to see if anything changed, and it went off
without a hitch. My record has been sent to the site.

**Comment by Difegue** [comment]
Well, as far as I'm concerned this is fixed then! 😁 There's a little delay sometimes before a Wii with Showcase recognizes DoujinSoft as a valid recipient. Thanks for the record!
