### ISSUE TITLE
Request: Section for DIY Showcase .mios

### ISSUE THREAD

**Issue by BobRocks20** [Difegue/DoujinSoft#14]
the diy showcase channel has an option to transfer its built-in games to the ds, and while that's cool I've been having some issues with the connectivity; once I'm connected to the wii and pick any option the connection gets interrupted.

this is where my request comes in. if this was added, there'll be a quicker way to get the diy showcase .mios without having to go through this wii-ds crap.

**Comment by Difegue** [comment]
You can get the official .mios for both the DS and Wii games off the Vixynyan collection: https://archive.org/details/WarioWareDIYDownloadableMicrogameCollection  

I don't plan on adding them to DoujinSoft as they're technically not downloadable/user-generated content.

**Comment by BobRocks20** [comment]
forgot about that, whoops. thanks anyway!
