### ISSUE TITLE
Unable to import anything into my save file

### ISSUE THREAD

**Issue by eisnerguy1** [Difegue/DoujinSoft#15]
So, I used [GodMode9i](https://github.com/DS-Homebrew/GodMode9i) to extract my save file from my cart. It's a fully functional save file as I'm able to load it in [DeSmuME](https://github.com/TASEmulators/desmume) and [TWiLightMenu](https://github.com/DS-Homebrew/TWiLightMenu). I'm also able to save changes to it as well. The problem is that it's a 16.78 mb save file though. I padded it with 16MB (0×1000000 bytes) of zeros in a hex editor. It's now a 33.55 mb save file. Whenever I try to inject things via Checkout, I get the error message "Invalid file."

Here's my unedited save file:
[DSMIO_UORE01_00.zip](https://github.com/Difegue/DoujinSoft/files/8176559/DSMIO_UORE01_00.zip)

And here's the padded save file:
[DSMIO_UORE01_00_padded.zip](https://github.com/Difegue/DoujinSoft/files/8176564/DSMIO_UORE01_00_padded.zip)

Is there some other way to make my save file compatible with DoujinSoft?

**Comment by Difegue** [comment]
The internal code used by DoujinSoft to handle DIY saves is the same as the one used by DIYEdit: https://www.romhacking.net/utilities/1008/  
As long as your save works with that software, it should work with the Checkout page.  

Padding with 16MB of zeroes _should_ be the normal way to have it accept 16MB save files (as per romhacking.net once again).  
I never really touched upon the save import/export code so I'm very unfamiliar with it, sadly 😅

**Comment by MacaylaMarvelous81** [comment]
I've been having trouble with this too for a while now; my save gets rejected by Checkout even after padding.

> As long as your save works with that software, it should work with the Checkout page.

I tried out the provided DSMIO_UORE01_00_padded file from eisnerguy1 with DIYEdit, and the padded one seems to work with DIYEdit and the unedited one does not. Unfortunately, they both result in an "Invalid file." message in the Checkout.

**Comment by Difegue** [comment]
Thanks for the extra information; If something's broken in dsoft but not in diyedit that gives me a starting point. 🤓  
I'll try to take a look, but no guarantees 😅  

While I'm at it, it might be doable to add support for 16MB savefiles as well. (probably just by doing the padding in-app)

**Comment by MacaylaMarvelous81** [comment]
`24-May-2022 04:57:40.625 SEVERE [http-nio-8080-exec-6] com.difegue.doujinsoft.CartServlet.doPost Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "com.difegue.doujinsoft.templates.Cart.getSaveFile()" is null`
Log entry after attempting to upload the save provided by eisnerguy1 to checkout in a DoujinSoft running in Codespaces
I think the error occurs on this line [(click for permalink)](https://github.com/Difegue/DoujinSoft/blob/2867bdf290a3eeaec8bed141147b777d5f19e474/src/com/difegue/doujinsoft/CartServlet.java#L168)
`SaveHandler sHand = new SaveHandler(cartData.getSaveFile().getAbsolutePath());`

**Comment by MacaylaMarvelous81** [comment]
By replacing `if (request.getParameterMap().containsKey("save"))` ([click for permalink](https://github.com/Difegue/DoujinSoft/blob/2867bdf290a3eeaec8bed141147b777d5f19e474/src/com/difegue/doujinsoft/templates/Cart.java#L28)) with `if (request.getPart("save") != null)`, I was able to checkout with eisnerguy1's padded save file.

**Comment by Difegue** [comment]
I've also modified DIYEdit to accept 16MB saves, so hopefully every problem here has now been fixed. 🚀
