### ISSUE TITLE
delete this issue after download/retriving that Europe exclusive Themesoft .mio "MiniGolf" that's locked exclusively to that European Wii save from GameFaqs.

### ISSUE THREAD

**Issue by McVirginleth0** [Difegue/DoujinSoft#39]
this is a quick issue to prove that "MiniGolf from the European Themesoft actually exists", after that delete this issue immediately. the WA4P-PAL save for WarioWare showcase called "warioware-diy-showcase.21432.bin" has a missing european exclusive themesoft micro "MiniGolf" from this Europe only Wii save https://gamefaqs.gamespot.com/wii/959422-warioware-diy-showcase/saves/21432 (i even went on the doujinsoft website, searched "MiniGolf" or author "Link" on EUR Themesoft or the Main page no results, not to mention let alone that there isn't even 1 single US save that contains this micro anywhere)
![a eu themesoft mio micro that is missing from doujinsoft](https://user-images.githubusercontent.com/127570646/224459367-fce46ba9-9ad3-4f8a-b7d9-e47a4cc83309.png)
[G-Link(them)-10012 (UE) (2010-07-09) (#) Minigolf.zip](https://github.com/Difegue/DoujinSoft/files/10947356/G-Link.them.-10012.UE.2010-07-09.Minigolf.zip)
are there any other mio files in these gamefaqs saves that are not on doujinsoft?, it's worth checking. https://gamefaqs.gamespot.com/wii/959422-warioware-diy-showcase/saves

**Comment by Difegue** [comment]
Added, thanks.  

(Just send an email next time if you don't want stuff to stick in a GH issue...)
