### ISSUE TITLE
504 Gateway time-out 

### ISSUE THREAD

**Issue by Pro70Crazy** [Difegue/DoujinSoft#48]
![Screenshot_20240102_171758_Chrome](https://github.com/Difegue/DoujinSoft/assets/69443748/8573faab-81be-4445-8681-e6bcdecb09d2)

**Comment by Difegue** [comment]
WiiLink24 mail has been shut down in favor of the existing RC24 mailserver; I've deployed a new version of DoujinSoft that should allow RC24 users to connect anew.  
Happy new year!
