### ISSUE TITLE
Pre-Microgame intros are too fast

### ISSUE THREAD

**Issue by MK-Majro** [Difegue/DoujinSoft#50]
The little intros before microgames that show how many lives you have only last for a split second before making you play another microgame. The jingle also overlaps the microgames' music when this happens.

I'm using Firefox, if that matters.

**Comment by Difegue** [comment]
Hmm, I test on firefox as well but haven't encountered this.

**Comment by larsenv** [comment]
I've experienced this problem, not sure what the problem is. I only experience it on my M1 Pro MacBook Pro with any web browser and not any other machine

**Comment by Ruffianlab1** [comment]
@MK-Majro @Difegue @larsenv I was having this same issue and I figured out how to fix it, please check "Don't disable the prefers-reduced-motion media query" via http://animate.style/#best-practices
