### ISSUE TITLE
MIDI samples may not be accurate

### ISSUE THREAD

**Issue by Ruffianlab1** [Difegue/DoujinSoft#62]
According to the sound effect file used by Showcase, each pitch for each instrument is stored as a different sample. The effect of the baby instrument intensifies with each pitch, so trying to recreate this using soundfont won't be accurate

**Comment by Difegue** [comment]
It would be pretty hard to implement pitching differences with multiple samples -- This is more of a mio-micro/mio-midi problem however, I'm entirely reliant on those libraries for music playing these days.  

Feel free to open this issue against https://github.com/yeahross0/Mio-Micro 👍
